<a href="https://colab.research.google.com/github/Anand-Swaroop-Inedi/EarthQuakePrediction/blob/main/EarthQuakePrediction1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np#importing the numpy module
import pandas as pd#importing the pandas module

from sklearn.model_selection import train_test_split#importing the train test split module

import pickle #import pickle
from sklearn import metrics #import metrics
from sklearn.ensemble import RandomForestClassifier#import the Random Forest Classifier

In [ ]:
data= pd.read_csv("database.csv")
import datetime
import time
timestamp = []
for d, t in zip(data['Date'], data['Time']):
    try:
        ts = datetime.datetime.strptime(d+' '+t, '%m/%d/%Y %H:%M:%S')
        timestamp.append(time.mktime(ts.timetuple()))
    except ValueError:
        timestamp.append('ValueError')
timeStamp = pd.Series(timestamp)
data['Timestamp'] = timeStamp.values
final_data = data.drop(['Date', 'Time'], axis=1)
final_data = final_data[final_data.Timestamp != 'ValueError']
final_data.head()

Latitude  Longitude        Type  Depth  Depth Error  \
0    19.246    145.616  Earthquake  131.6          NaN   
1     1.863    127.352  Earthquake   80.0          NaN   
2   -20.579   -173.972  Earthquake   20.0          NaN   
3   -59.076    -23.557  Earthquake   15.0          NaN   
4    11.938    126.427  Earthquake   15.0          NaN   

   Depth Seismic Stations  Magnitude Magnitude Type  Magnitude Error  \
0                     NaN        6.0             MW              NaN   
1                     NaN        5.8             MW              NaN   
2                     NaN        6.2             MW              NaN   
3                     NaN        5.8             MW              NaN   
4                     NaN        5.8             MW              NaN   

   Magnitude Seismic Stations  Azimuthal Gap  Horizontal Distance  \
0                         NaN            NaN                  NaN   
1                         NaN            NaN                  NaN   
2                         NaN            NaN                  NaN   
3                         NaN            NaN                  NaN   
4                         NaN            NaN                  NaN   

   Horizontal Error  Root Mean Square            ID  Source Location Source  \
0               NaN               NaN  ISCGEM860706  ISCGEM          ISCGEM   
1               NaN               NaN  ISCGEM860737  ISCGEM          ISCGEM   
2               NaN               NaN  ISCGEM860762  ISCGEM          ISCGEM   
3               NaN               NaN  ISCGEM860856  ISCGEM          ISCGEM   
4               NaN               NaN  ISCGEM860890  ISCGEM          ISCGEM   

  Magnitude Source     Status    Timestamp  
0           ISCGEM  Automatic -157630542.0  
1           ISCGEM  Automatic -157465811.0  
2           ISCGEM  Automatic -157355642.0  
3           ISCGEM  Automatic -157093817.0  
4           ISCGEM  Automatic -157026430.0

In [ ]:
import matplotlib.pyplot as plt
X = final_data[['Timestamp', 'Latitude', 'Longitude','Depth']]
y = final_data[['Magnitude']]
X=X.astype('int')
y=y.astype('int')
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
from sklearn.preprocessing import StandardScaler
import torch
std_scaler=StandardScaler()

x_train_std=std_scaler.fit_transform(X_train)
x_test_std=std_scaler.fit_transform(X_test)


**Random Forest**


In [ ]:
from sklearn.ensemble import RandomForestClassifier
Random_forest_classifier = RandomForestClassifier()#creating the model
Random_forest_classifier.fit(x_train_std, y_train)#fitting the model with training dataset
y_pred = Random_forest_classifier.predict(x_test_std)#predicting the result using test set
cm=metrics.confusion_matrix(y_test,y_pred)
print(cm)
print("Precision score:%.3f"%metrics.precision_score(y_test,y_pred,average="micro"))
print("Recall score:%.3f"%metrics.recall_score(y_test,y_pred,average="micro"))
print("f1-score:%.3f"%metrics.f1_score(y_test,y_pred,average="micro"))
print("Accuracy:%.3f"%metrics.accuracy_score(y_test, y_pred))#printing the accuracy score

<ipython-input-6-125ba26810f8>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  Random_forest_classifier.fit(x_train_std, y_train)#fitting the model with training dataset


[[2787  441    9    1    0]
 [ 955  321    9    1    0]
 [ 101   46    0    0    0]
 [   4    6    0    0    0]
 [   1    0    0    0    0]]
Precision score:0.664
Recall score:0.664
f1-score:0.664
Accuracy:0.664


**Gradient Boosting Algorithm**

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
tree = GradientBoostingClassifier() #making an instance the descision tree with maxdepth = 3 as passing the input
clf = tree.fit(x_train_std,y_train) #here we are passing our training and the testing data to the tree and fitting it

y_pred = clf.predict(x_test_std) #predicting the value by passing the x_test datset to the tree
cm=metrics.confusion_matrix(y_test,y_pred)
print(cm)
print("Precision score:%.3f"%metrics.precision_score(y_test,y_pred,average="micro"))
print("Recall score:%.3f"%metrics.recall_score(y_test,y_pred,average="micro"))
print("f1-score:%.3f"%metrics.f1_score(y_test,y_pred,average="micro"))
print("Accuracy:%.3f"%metrics.accuracy_score(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_gb.py:437: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[3171   62    2    3    0]
 [1213   67    4    2    0]
 [ 142    5    0    0    0]
 [   8    2    0    0    0]
 [   1    0    0    0    0]]
Precision score:0.692
Recall score:0.692
f1-score:0.692
Accuracy:0.692


**Support Vector Classifier**

In [ ]:
from sklearn import svm
tree = svm.SVC(gamma='auto') #making an instance the support vector tree
clf = tree.fit(x_train_std,y_train) #here we are passing our training and the testing data to the tree and fitting it
y_pred = clf.predict(x_test_std) #predicting the value by passing the x_test datset to the tree
cm=metrics.confusion_matrix(y_test,y_pred)
print(cm)
print("Precision score:%.3f"%metrics.precision_score(y_test,y_pred,average="micro"))
print("Recall score:%.3f"%metrics.recall_score(y_test,y_pred,average="micro"))
print("f1-score:%.3f"%metrics.f1_score(y_test,y_pred,average="micro"))
print("Accuracy:%.3f"%metrics.accuracy_score(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[3237    1    0    0    0]
 [1283    3    0    0    0]
 [ 146    1    0    0    0]
 [  10    0    0    0    0]
 [   1    0    0    0    0]]
Precision score:0.692
Recall score:0.692
f1-score:0.692
Accuracy:0.692
